---
title: "Returns Distribution"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---

###getting the required libraries 
```{r setup, message = FALSE}
library(tidyverse)
library(highcharter)
library(tidyquant)
library(timetk)
```

Sidebar {.sidebar}
=====================================


###creating columns, input data 
```{r}

fluidRow(
  column(6,
  textInput("stock1", "Stock 1", "TWTR")),
  column(5,
  numericInput("w1", "Portf. %", 15, min = 1, max = 100))
)  

fluidRow(
  column(6,
  textInput("stock2", "Stock 2", "AAPL")),
  column(5,
  numericInput("w2", "Portf. %", 15, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Stock 3", "TSLA")),
  column(5,
  numericInput("w3", "Portf. %", 30, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Stock 4", "NKE")),
  column(5,
  numericInput("w4", "Portf. %", 10, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Stock 5", "BA")),
  column(5,
  numericInput("w5", "Portf. %", 5, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock6", "Stock 6", "KO")),
  column(5,
  numericInput("w6", "Portf. %", 5, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock7", "Stock 7", "MSFT")),
  column(5,
  numericInput("w7", "Portf. %", 20, min = 1, max = 100))
)


###start date
fluidRow(
  column(7,
  dateInput("date", "Starting Date", "2018-01-01", format = "yyyy-mm-dd"))
)

###rebalancing options
fluidRow(
  column(7,
  selectInput("rebalance", "rebalance freq",
              c("Yearly" = "years",
                "Monthly" = "months",
                "Weekly" = "weeks"))
  )
)

### action button 
actionButton("go", "Submit")

###portfolio returns calculation 
portfolio_returns_byhand <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5, input$stock6, input$stock7)
  
  prices <- getSymbols(symbols, src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
    `colnames<-`(symbols)

  w <- c(input$w1/100, input$w2/100, 
         input$w3/100, input$w4/100, input$w5/100, input$w6/100, input$w7/100)
  
  asset_returns_long <- 
      prices %>% 
      to.monthly(indexAt = "last", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns))))

  portfolio_returns_byhand <- 
    asset_returns_long %>% 
    tq_portfolio(assets_col = asset, 
               returns_col = returns, 
               weights = w,
               col_rename = "returns")
  
})

```

Returns
=====================================  


Row {.tabset .tabset-fade}
-------------------------------------



### Histogram + Density

```{r}
renderPlot({
  portfolio_returns_byhand() %>% 
    ggplot(aes(x = returns)) +
    geom_histogram(alpha = 1, binwidth = .01, fill = "lawngreen") +
    geom_density(geom = "line", size = 0.5, color = "royalblue1")+
    theme_dark()
})
```








